{% set version = "0.1.5" %}

package:
  name: spiffe-packages
  version: {{ version }}


source:
  - url: https://pypi.org/packages/source/s/spiffe/spiffe-{{ version }}.tar.gz
    sha256: 7f3c34907d4c5bce75700e3f5f60cab80c0a28a6ea8b2df7e7ed2f4c16a3579f
    folder: spiffe
  - url: https://pypi.org/packages/source/s/spiffe-tls/spiffe_tls-{{ version }}.tar.gz
    sha256: 3dd792407d3fcfae544a563897fbec61ac141afbfacb67998ad733204fe3392c
    folder: spiffe-tls

build:
  number: 0
  noarch: python

outputs:
  - name: spiffe
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd spiffe
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python >=3.9
        - pip
        - poetry-core >=1.9.0
      run:
        - python >=3.9
        - grpcio >=1.62
        - cryptography >=42
        - pyjwt >=2
        - pyasn1
        - pyasn1-modules
        - protobuf
        - pem >=23
    test:
      imports:
        - spiffe

  - name: spiffe-tls
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd spiffe-tls
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python >=3.9
        - pip
        - poetry-core >=1.9.0
      run:
        - python >=3.9
        - pyopenssl >=24
        - spiffe
      run_constrained:
        - spiffe ={{ version }}
    test:
      imports:
        - spiffetls

about:
  home: https://github.com/HewlettPackard/py-spiffe
  license: Apache-2.0
  license_file: spiffe/LICENSE
  summary: Python library for SPIFFE support
  dev_url: https://github.com/HewlettPackard/py-spiffe

extra:
  recipe-maintainers:
    - martinRenou
