{% set version = "0.1.3" %}

package:
  name: spiffe-packages
  version: {{ version }}


source:
  - url: https://pypi.io/packages/source/s/spiffe/spiffe-{{ version }}.tar.gz
    sha256: 69c686522cefb0193eae150153544312f794c8c9c1537a25695b2b54164cb717
    folder: spiffe
  - url: https://pypi.io/packages/source/s/spiffe-tls/spiffe_tls-{{ version }}.tar.gz
    sha256: 56497622188d81ee137c76c80eb96625b3a9c0ca466021cce6136ce2fc0ddb57
    folder: spiffe-tls

build:
  number: 0
  noarch: python

outputs:
  - name: spiffe
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd spiffe
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python >=3.9
        - pip
        - poetry-core >=1.9.0
      run:
        - python >=3.9
        - grpcio >=1.62
        - cryptography >=42
        - pyjwt >=2
        - pyasn1
        - pyasn1-modules
        - protobuf
        - pem >=23
    test:
      imports:
        - spiffe

  - name: spiffe-tls
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd spiffe-tls
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python >=3.9
        - pip
        - poetry-core >=1.9.0
      run:
        - python >=3.9
        - pyopenssl >=24
        - spiffe
      run_constrained:
        - spiffe ={{ version }}
    test:
      imports:
        - spiffetls

about:
  home: https://github.com/HewlettPackard/py-spiffe
  license: Apache-2.0
  license_file: spiffe/LICENSE
  summary: Python library for SPIFFE support
  dev_url: https://github.com/HewlettPackard/py-spiffe

extra:
  recipe-maintainers:
    - martinRenou
